version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_APP_SECRET_KEY_BASE: $(bin/rails secret)
      RAILS_APP_JWT_SECRET_KEY: auth-service
      RAILS_APP_CLIENT_BASE_URL: http://localhost:5173
      RAILS_APP_SERVER_BASE_URL: http://localhost:3000
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
