name: auth-service-api

services:
  api:
    build:
      context: .
      dockerfile: ${RAILS_DOCKERFILE}
    environment:
      RAILS_REDIS_URL: ${RAILS_REDIS_URL}
      MAIL_MAILER: ${MAIL_MAILER}
      MAIL_FALLBACK_MAILERS: ${MAIL_FALLBACK_MAILERS}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
      RESEND_API_KEY: ${RESEND_API_KEY}
      POSTMARK_TOKEN: ${POSTMARK_TOKEN}
      STRIPE_KEY: ${STRIPE_KEY}
      STRIPE_SECRET: ${STRIPE_SECRET}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
    volumes:
      - .:/rails
    ports:
      - ${RAILS_PORT_MAP}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:18-alpine
    volumes:
      - postgres:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - ${PG_PORT_MAP}

  redis:
    image: redis:8.8-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 10
    ports:
      - ${REDIS_PORT_MAP}

volumes:
  postgres:
